# Generated by Django 4.2.7 on 2023-12-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('equity_file_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('bse_code', models.CharField(max_length=50)),
                ('nse_code', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=200)),
                ('current_price', models.FloatField(default=0.0)),
                ('market_capitalization', models.FloatField(default=0.0)),
                ('price_to_earning', models.FloatField(default=0.0)),
                ('industry_pe', models.FloatField(default=0.0)),
                ('eps', models.FloatField(default=0.0)),
            ],
        ),
    ]
