# Generated by Django 4.2.7 on 2023-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_file_alter_equity_files_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equity_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('equity_filter_name', models.CharField(max_length=200)),
                ('parameter_name', models.CharField(max_length=100)),
                ('condition_1', models.CharField(max_length=10)),
                ('value_1', models.CharField(max_length=10000)),
                ('result_1', models.CharField(max_length=10)),
                ('condition_2', models.CharField(max_length=10)),
                ('value_2', models.CharField(max_length=10000)),
                ('result_2', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='equity_files',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
