# Generated by Django 4.2.7 on 2023-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0003_equity_filter_alter_equity_files_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('angel_user', models.CharField(max_length=100)),
                ('angel_pwd', models.CharField(max_length=100)),
                ('pan', models.IntegerField()),
                ('aadhar', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('fin_q', models.IntegerField()),
                ('totpkey', models.CharField(max_length=500)),
                ('initialdeposit', models.FloatField()),
                ('available_margin', models.FloatField()),
                ('lotsize', models.IntegerField()),
                ('signupdate', models.DateTimeField()),
                ('createdate', models.DateTimeField()),
                ('apikey', models.CharField(max_length=500)),
                ('asmita_apikey', models.CharField(max_length=500)),
                ('ha_apikey', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
                ('strategyflag', models.IntegerField()),
                ('user_table_id', models.IntegerField()),
            ],
        ),
    ]
